USE [OMS]
GO
/****** Object:  Table [dbo].[TB_ALERTAS]    Script Date: 08/23/2011 10:41:49 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [dbo].[TB_ALERTAS](
	[IdAlerta] [char](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[IdCliente] [varchar](20) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[Instrumento] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[TipoOperando] [int] NOT NULL,
	[TipoOperador] [int] NOT NULL,
	[Valor] [decimal](23, 9) NOT NULL,
	[Atingido] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[Exibido] [char](1) COLLATE SQL_Latin1_General_CP1_CI_AS NULL,
	[DataCadastro] [datetime] NULL,
	[DataAtingimento] [datetime] NULL,
	[Cotacao] [decimal](23, 9) NULL,
 CONSTRAINT [PK_TB_ALERTAS] PRIMARY KEY CLUSTERED 
(
	[IdAlerta] ASC
)WITH (PAD_INDEX  = OFF, IGNORE_DUP_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [dbo].[TB_ALERTAS]  WITH CHECK ADD  CONSTRAINT [FK_TB_ALERTAS_TB_ALERTAS_OPERADOR] FOREIGN KEY([TipoOperador])
REFERENCES [dbo].[TB_ALERTAS_OPERADOR] ([Tipo])
GO
ALTER TABLE [dbo].[TB_ALERTAS] CHECK CONSTRAINT [FK_TB_ALERTAS_TB_ALERTAS_OPERADOR]
GO
ALTER TABLE [dbo].[TB_ALERTAS]  WITH CHECK ADD  CONSTRAINT [FK_TB_ALERTAS_TB_ALERTAS_OPERANDO] FOREIGN KEY([TipoOperando])
REFERENCES [dbo].[TB_ALERTAS_OPERANDO] ([Tipo])
GO
ALTER TABLE [dbo].[TB_ALERTAS] CHECK CONSTRAINT [FK_TB_ALERTAS_TB_ALERTAS_OPERANDO]