///////////////////////////////////////////////////////////
//  ListarPermissoesRiscoResponse.cs
//  Implementation of the Class ListarPermissoesRiscoResponse
//  Generated by Enterprise Architect
//  Created on:      26-jul-2010 17:43:26
//  Original author: amiguel
///////////////////////////////////////////////////////////


using System.Collections.Generic;
using Gradual.OMS.Risco.RegraLib.Dados;
using Gradual.OMS.Library;


namespace Gradual.OMS.Risco.RegraLib.Mensagens 
{
	public class ListarPermissoesRiscoResponse : MensagemResponseBase
    {

		public ListarPermissoesRiscoResponse()
        {

		}

        public List<PermissaoRiscoInfo> Permissoes { get; set; }

		~ListarPermissoesRiscoResponse()
        {

		}

	}//end ListarPermissoesRiscoResponse

}//end namespace Mensagens