///////////////////////////////////////////////////////////
//  ListarParametrosRiscoRequest.cs
//  Implementation of the Class ListarParametrosRiscoRequest
//  Generated by Enterprise Architect
//  Created on:      26-jul-2010 17:43:16
//  Original author: amiguel
///////////////////////////////////////////////////////////




using Gradual.OMS.Risco.RegraLib.Dados;
using Gradual.OMS.Library;
namespace Gradual.OMS.Risco.RegraLib.Mensagens {
	public class ListarParametrosRiscoRequest : MensagemRequestBase {

		public ListarParametrosRiscoRequest()
        {
		}

        public BolsaInfo Bolsa { get; set; }

        public string FiltroNomeParamertro { get; set; }


		~ListarParametrosRiscoRequest()
        {
		}

	}//end ListarParametrosRiscoRequest

}//end namespace Mensagens