///////////////////////////////////////////////////////////
//  ListarParametrosRiscoClienteRequest.cs
//  Implementation of the Class ListarParametrosRiscoClienteRequest
//  Generated by Enterprise Architect
//  Created on:      26-jul-2010 17:43:16
//  Original author: amiguel
///////////////////////////////////////////////////////////





using Gradual.OMS.Library;
namespace Gradual.OMS.Risco.RegraLib.Mensagens {
	public class ListarParametrosRiscoClienteRequest : MensagemRequestBase {

		public ListarParametrosRiscoClienteRequest(){

		}

        public int CodigoCliente { get; set; }

		~ListarParametrosRiscoClienteRequest(){

		}

	}//end ListarParametrosRiscoClienteRequest

}//end namespace Mensagens