//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.2034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.2034.
// 
#pragma warning disable 1591

namespace AppTesteWSZara.br.com.gradualinvestimentos.wszarathustra {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WSTraderBeanSoap", Namespace="http://wszarathustra.gradualinvestimentos.com.br/")]
    public partial class WSTraderBean : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetBeansOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WSTraderBean() {
            this.Url = global::AppTesteWSZara.Properties.Settings.Default.AppTesteWSZara_br_com_gradualinvestimentos_wszarathustra_WSTraderBean;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetBeansCompletedEventHandler GetBeansCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://wszarathustra.gradualinvestimentos.com.br/WSZarathustra/WSTraderBean/GetBe" +
            "ans", RequestNamespace="http://wszarathustra.gradualinvestimentos.com.br/WSZarathustra/WSTraderBean", ResponseNamespace="http://wszarathustra.gradualinvestimentos.com.br/WSZarathustra/WSTraderBean", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public traderBean[] GetBeans(string pUser, string pPassword, string pTradeID) {
            object[] results = this.Invoke("GetBeans", new object[] {
                        pUser,
                        pPassword,
                        pTradeID});
            return ((traderBean[])(results[0]));
        }
        
        /// <remarks/>
        public void GetBeansAsync(string pUser, string pPassword, string pTradeID) {
            this.GetBeansAsync(pUser, pPassword, pTradeID, null);
        }
        
        /// <remarks/>
        public void GetBeansAsync(string pUser, string pPassword, string pTradeID, object userState) {
            if ((this.GetBeansOperationCompleted == null)) {
                this.GetBeansOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBeansOperationCompleted);
            }
            this.InvokeAsync("GetBeans", new object[] {
                        pUser,
                        pPassword,
                        pTradeID}, this.GetBeansOperationCompleted, userState);
        }
        
        private void OnGetBeansOperationCompleted(object arg) {
            if ((this.GetBeansCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBeansCompleted(this, new GetBeansCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.2022")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://wszarathustra.gradualinvestimentos.com.br/WSZarathustra/WSTraderBean")]
    public partial class traderBean {
        
        private string idField;
        
        private string dATA_NEGOCIOField;
        
        private string hORA_NEGOCIOField;
        
        private string nR_NEGOCIOField;
        
        private string cODNEGField;
        
        private string sERPAPField;
        
        private string oPERACAOField;
        
        private string qTDADEField;
        
        private string pDENEGField;
        
        private string fC_NOMEField;
        
        private string nM_EMIT_ORDEMField;
        
        private string mERCADOField;
        
        /// <remarks/>
        public string ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string DATA_NEGOCIO {
            get {
                return this.dATA_NEGOCIOField;
            }
            set {
                this.dATA_NEGOCIOField = value;
            }
        }
        
        /// <remarks/>
        public string HORA_NEGOCIO {
            get {
                return this.hORA_NEGOCIOField;
            }
            set {
                this.hORA_NEGOCIOField = value;
            }
        }
        
        /// <remarks/>
        public string NR_NEGOCIO {
            get {
                return this.nR_NEGOCIOField;
            }
            set {
                this.nR_NEGOCIOField = value;
            }
        }
        
        /// <remarks/>
        public string CODNEG {
            get {
                return this.cODNEGField;
            }
            set {
                this.cODNEGField = value;
            }
        }
        
        /// <remarks/>
        public string SERPAP {
            get {
                return this.sERPAPField;
            }
            set {
                this.sERPAPField = value;
            }
        }
        
        /// <remarks/>
        public string OPERACAO {
            get {
                return this.oPERACAOField;
            }
            set {
                this.oPERACAOField = value;
            }
        }
        
        /// <remarks/>
        public string QTDADE {
            get {
                return this.qTDADEField;
            }
            set {
                this.qTDADEField = value;
            }
        }
        
        /// <remarks/>
        public string PDENEG {
            get {
                return this.pDENEGField;
            }
            set {
                this.pDENEGField = value;
            }
        }
        
        /// <remarks/>
        public string FC_NOME {
            get {
                return this.fC_NOMEField;
            }
            set {
                this.fC_NOMEField = value;
            }
        }
        
        /// <remarks/>
        public string NM_EMIT_ORDEM {
            get {
                return this.nM_EMIT_ORDEMField;
            }
            set {
                this.nM_EMIT_ORDEMField = value;
            }
        }
        
        /// <remarks/>
        public string MERCADO {
            get {
                return this.mERCADOField;
            }
            set {
                this.mERCADOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void GetBeansCompletedEventHandler(object sender, GetBeansCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBeansCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBeansCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public traderBean[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((traderBean[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591