//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.Intranet.Www.Intranet.Risco.Formularios.Dados {
    
    
    public partial class AssociarPermissoesParametros {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// hidRisco_AssociarPermissoesParametros_ListaJson control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidRisco_AssociarPermissoesParametros_ListaJson;
        
        /// <summary>
        /// hidRisco_AssociarPermissoesParametros_CBLC control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidRisco_AssociarPermissoesParametros_CBLC;
        
        /// <summary>
        /// hidRisco_AssociarPermissoesParametros_BMF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidRisco_AssociarPermissoesParametros_BMF;
        
        /// <summary>
        /// hidRisco_ListaPermissoesAssociadas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidRisco_ListaPermissoesAssociadas;
        
        /// <summary>
        /// rpt_Risco_AssociarPermissoesParametros_Parametros control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rpt_Risco_AssociarPermissoesParametros_Parametros;
        
        /// <summary>
        /// rpt_Risco_AssociarPermissoesParametros_Grupo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rpt_Risco_AssociarPermissoesParametros_Grupo;
        
        /// <summary>
        /// rpt_Risco_AssociarPermissoesParametros_Permissoes_chk control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rpt_Risco_AssociarPermissoesParametros_Permissoes_chk;
    }
}
