//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.Intranet.Www.Intranet.Clientes.Formularios.Acoes {
    
    
    public partial class ConfigurarLimitesNovoOMS {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// hidClienteLimites control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hidClienteLimites;
        
        /// <summary>
        /// pnlCliente_Limites_Bovespa_Painel_Esquerda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlCliente_Limites_Bovespa_Painel_Esquerda;
        
        /// <summary>
        /// chkCliente_Limites_Bosvespa_AVista_Opera_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkCliente_Limites_Bosvespa_AVista_Opera_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bosvespa_AVista_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bosvespa_AVista_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bosvespa_AVista_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bosvespa_AVista_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_AVista_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_AVista_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_AVista_Alocado_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_AVista_Alocado_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_AVista_Disponivel_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_AVista_Disponivel_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bosvespa_AVista_DataDeVencimento_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bosvespa_AVista_DataDeVencimento_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bosvespa_AVista_DataDeVencimento_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bosvespa_AVista_DataDeVencimento_NovoOMS;
        
        /// <summary>
        /// pnlLinksParametroLimiteOperaAVista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlLinksParametroLimiteOperaAVista;
        
        /// <summary>
        /// pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_OperaAVista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_OperaAVista;
        
        /// <summary>
        /// chkCliente_Limites_Bosvespa_AVista_OperaDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkCliente_Limites_Bosvespa_AVista_OperaDescoberto_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bosvespa_AVista_LimiteDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bosvespa_AVista_LimiteDescoberto_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bosvespa_AVista_LimiteDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bosvespa_AVista_LimiteDescoberto_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_AVista_Descoberto_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_AVista_Descoberto_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_AVista_Descoberto_Alocado_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_AVista_Descoberto_Alocado_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_AVista_Descoberto_Disponivel_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_AVista_Descoberto_Disponivel_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bosvespa_AVista_DataDeVencimentoDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bosvespa_AVista_DataDeVencimentoDescoberto_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bosvespa_AVista_DataDeVencimentoDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bosvespa_AVista_DataDeVencimentoDescoberto_NovoOMS;
        
        /// <summary>
        /// pnlLinksParametroLimiteOperaAVistaDescoberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlLinksParametroLimiteOperaAVistaDescoberto;
        
        /// <summary>
        /// pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_AVistaDescoberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_AVistaDescoberto;
        
        /// <summary>
        /// pnlCliente_Limites_Bovespa_Painel_direito control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlCliente_Limites_Bovespa_Painel_direito;
        
        /// <summary>
        /// chkCliente_Limites_Bovespa_Opcao_Opera_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkCliente_Limites_Bovespa_Opcao_Opera_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bovespa_Opcao_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bovespa_Opcao_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bovespa_Opcao_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bovespa_Opcao_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_Opcoes_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_Opcoes_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_Opcoes_Alocado_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_Opcoes_Alocado_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_Opcoes_Disponivel_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_Opcoes_Disponivel_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bovespa_Opcao_DataDeVencimento_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bovespa_Opcao_DataDeVencimento_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bovespa_Opcao_DataDeVencimento_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bovespa_Opcao_DataDeVencimento_NovoOMS;
        
        /// <summary>
        /// pnlLinksParametroLimiteOperaOpcao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlLinksParametroLimiteOperaOpcao;
        
        /// <summary>
        /// pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_OperaOpcao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_OperaOpcao;
        
        /// <summary>
        /// chkCliente_Limites_Bovespa_Opcao_OperaDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkCliente_Limites_Bovespa_Opcao_OperaDescoberto_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bovespa_Opcao_LimiteDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bovespa_Opcao_LimiteDescoberto_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bovespa_Opcao_LimiteDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bovespa_Opcao_LimiteDescoberto_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_Opcoes_Descoberto_Limite_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_Opcoes_Descoberto_Limite_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_Opcoes_Descoberto_Alocado_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_Opcoes_Descoberto_Alocado_NovoOMS;
        
        /// <summary>
        /// txtCliente_Detalhes_Opcoes_Descoberto_Disponivel_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Detalhes_Opcoes_Descoberto_Disponivel_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bovespa_Opcao_DataDeVencimentoDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bovespa_Opcao_DataDeVencimentoDescoberto_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bovespa_Opcao_DataDeVencimentoDescoberto_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bovespa_Opcao_DataDeVencimentoDescoberto_NovoOMS;
        
        /// <summary>
        /// pnlLinksParametroLimiteOperaOpcaoDescoberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlLinksParametroLimiteOperaOpcaoDescoberto;
        
        /// <summary>
        /// pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_OpcaoDescoberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_OpcaoDescoberto;
        
        /// <summary>
        /// divParametroLimiteValorMaximoDaOrdem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl divParametroLimiteValorMaximoDaOrdem;
        
        /// <summary>
        /// chkCliente_Limites_Bovespa_ValorMaximoDaOrdem_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputCheckBox chkCliente_Limites_Bovespa_ValorMaximoDaOrdem_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bovespa_ValorMaximoDaOrdem_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bovespa_ValorMaximoDaOrdem_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bovespa_ValorMaximoDaOrdem_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bovespa_ValorMaximoDaOrdem_NovoOMS;
        
        /// <summary>
        /// hddCliente_Limites_Bosvespa_ValorMaximoDaOrdem_DataDeVencimento_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputHidden hddCliente_Limites_Bosvespa_ValorMaximoDaOrdem_DataDeVencimento_NovoOMS;
        
        /// <summary>
        /// txtCliente_Limites_Bosvespa_ValorMaximoDaOrdem_DataDeVencimento_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Limites_Bosvespa_ValorMaximoDaOrdem_DataDeVencimento_NovoOMS;
        
        /// <summary>
        /// pnlLinksParametroLimiteValorMaximoDaOrdem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlLinksParametroLimiteValorMaximoDaOrdem;
        
        /// <summary>
        /// pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_MaximoDaOrdem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlAnchor pnlCliente_Limites_Bovespa_Painel_lnkRenovarLimite_MaximoDaOrdem;
        
        /// <summary>
        /// rptCliente_Permissoes_NovoOMS control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCliente_Permissoes_NovoOMS;
        
        /// <summary>
        /// btnClientes_Limites_Bovespa control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl btnClientes_Limites_Bovespa;
        
        /// <summary>
        /// rptCliente_ResticoesPorGrupoAVista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCliente_ResticoesPorGrupoAVista;
        
        /// <summary>
        /// rptCliente_ResticoesPorGrupoAVistaDescoberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCliente_ResticoesPorGrupoAVistaDescoberto;
        
        /// <summary>
        /// rptCliente_ResticoesPorGrupoOpcoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCliente_ResticoesPorGrupoOpcoes;
        
        /// <summary>
        /// rptCliente_ResticoesPorGrupoOpcoesDescoberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCliente_ResticoesPorGrupoOpcoesDescoberto;
        
        /// <summary>
        /// btnGradIntra_Clientes_Restricoes_RestricaoPorAtivos_NovoOMS_Add control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputButton btnGradIntra_Clientes_Restricoes_RestricaoPorAtivos_NovoOMS_Add;
        
        /// <summary>
        /// btnGradIntra_Clientes_Restricoes_RestricaoPorAtivos_Remover_click control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnGradIntra_Clientes_Restricoes_RestricaoPorAtivos_Remover_click;
        
        /// <summary>
        /// rptCliente_RestricaoPorAtivo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptCliente_RestricaoPorAtivo;
        
        /// <summary>
        /// btnCliente_Restricoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnCliente_Restricoes;
    }
}
