//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.Intranet.Www.Intranet.Clientes.Formularios.Acoes {
    
    
    public partial class SpiderLimitesBMF {
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// btnClientes_Atualizar_Dados_Limites_BMF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnClientes_Atualizar_Dados_Limites_BMF;
        
        /// <summary>
        /// rptClientes_Contratos control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Repeater rptClientes_Contratos;
        
        /// <summary>
        /// txtCliente_Spider_Qtde_Compra control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Qtde_Compra;
        
        /// <summary>
        /// txtCliente_Spider_Qtde_Venda control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Qtde_Venda;
        
        /// <summary>
        /// txtCliente_Spider_Data_validade control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Data_validade;
        
        /// <summary>
        /// txtCliente_Spider_Instrumento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Instrumento;
        
        /// <summary>
        /// txtCliente_Spider_Qtde_Venda_Instrumento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Qtde_Venda_Instrumento;
        
        /// <summary>
        /// txtCliente_Spider_Qtde_Compra_Instrumento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Qtde_Compra_Instrumento;
        
        /// <summary>
        /// txtCliente_Spider_Qtde_Maxima_Ordem_Instrumento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Qtde_Maxima_Ordem_Instrumento;
        
        /// <summary>
        /// txtCliente_Spider_Qtde_Maxima_Ordem_Contrato control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCliente_Spider_Qtde_Maxima_Ordem_Contrato;
        
        /// <summary>
        /// btnClientes_Spider_Limites_BMF_Salvar control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlButton btnClientes_Spider_Limites_BMF_Salvar;
    }
}
