///////////////////////////////////////////////////////////
//  AutomacaoInfo.cs
//  Implementation of the Class AutomacaoInfo
//  Generated by Enterprise Architect
//  Created on:      23-abr-2010 15:31:12
//  Original author: amiguel
///////////////////////////////////////////////////////////




using Gradual.OMS.Contratos.Automacao.Ordens.Dados;
using Gradual.OMS.Contratos.Ordens;
using System.Collections.Generic;
using Gradual.OMS.Contratos.Ordens.Dados;
using System;
using System.Runtime.Serialization;
using System.ServiceModel;
namespace Gradual.OMS.Contratos.Automacao.Ordens.Dados {
    [Serializable]
    [DataContract]
    [ServiceKnownType(typeof(AutomacaoPrecosTaxasInfo))]
    public class AutomacaoInfo
    {
        [DataMember]
        public ItemAutomacaoStatusEnum AutomacaoStatus { get; set; }
        [DataMember]
        public ItemAutomacaoTipoEnum AutomacaoTipo { get; set; }
        [DataMember]
        public string CodigoBolsa { get; set; }
        [DataMember]
        public string CodigoCliente { get; set; }
        [DataMember]
        public string Instrumento { get; set; }
        [DataMember]
        public OrdemDirecaoEnum OrdemDirecao { get; set; }
        [DataMember]
        public List<AutomacaoPrecosTaxasInfo> PrecosTaxas { get; set; }
        [DataMember]
        public decimal Quantidade { get; set; }

        //public OrdemInfo OrdemInfo { get; set; }
        public AutomacaoInfo()
        {
            PrecosTaxas = new List<AutomacaoPrecosTaxasInfo>();
        }//end AutomacaoInfo
    }
}//end namespace Dados