///////////////////////////////////////////////////////////
//  AutomacaoPrecosTaxasInfo.cs
//  Implementation of the Class AutomacaoPrecosTaxasInfo
//  Generated by Enterprise Architect
//  Created on:      23-abr-2010 15:40:26
//  Original author: amiguel
///////////////////////////////////////////////////////////
using System;
using System.Runtime.Serialization;

namespace Gradual.OMS.Contratos.Automacao.Ordens.Dados {
	[Serializable]
    [DataContract]
    public class AutomacaoPrecosTaxasInfo {
        [DataMember]
        public ItemAutomacaoTipoEnum AutomacaoTipo { get; set; }
        [DataMember]
        public decimal PrecoEnvio { get; set; }
        [DataMember]
        public decimal PrecoGatilho { get; set; }
        [DataMember]
        public decimal TaxaAjusteInicio { get; set; }
        [DataMember]
        public decimal TaxaAjusteMovel { get; set; }

		public AutomacaoPrecosTaxasInfo(){

		}

	}//end AutomacaoPrecosTaxasInfo

}//end namespace Dados