///////////////////////////////////////////////////////////
//  ItemAutomacaoStatusEnum.cs
//  Implementation of the Class ItemAutomacaoStatusEnum
//  Generated by Enterprise Architect
//  Created on:      23-abr-2010 15:31:03
//  Original author: amiguel
///////////////////////////////////////////////////////////




using System;
namespace Gradual.OMS.Contratos.Automacao.Ordens.Dados {
    [Serializable]
    public enum ItemAutomacaoStatusEnum : int
    {

        RegistradoNaAplicacao = 1,
        AceitoPeloMDS = 2,
        RejeitadoPeloMDS = 3,
        EnviadoParaServidorDeOrdens = 4,
        ExecutadoPeloMDS = 5,
        CanceladoPeloMDS = 6,
        CancelamentoEnviado = 7,
        CancelamentoAceito = 9,
        AguardandoExecucaoDaOrdem = 8


	}//end ItemAutomacaoStatusEnum

}//end namespace Dados