//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.OMS.TesouroDireto.WSTDVenda {


    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "vendaSoap", Namespace = "http://www.cblc.com.br/")]
    public partial class venda : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private hdSeguranca hdSegurancaValueField;

        private System.Threading.SendOrPostCallback VendaInsCestaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaInsItemCestaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaAltItemCestaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaFecharCestaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaConsCestaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaConsCestaItensOperationCompleted;

        private System.Threading.SendOrPostCallback VendaVerifCondVendaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaVerifTitMercadoOperationCompleted;

        private System.Threading.SendOrPostCallback VendaConsTitMercadoOperationCompleted;

        private System.Threading.SendOrPostCallback VendaConsTitVendaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaConsValorTaxaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaConsValTxProvisoriaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaExclCestaOperationCompleted;

        private System.Threading.SendOrPostCallback VendaExclItemCestaOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public venda()
        {
            this.Url = global::Gradual.OMS.TesouroDireto.Properties.Settings.Default.Gradual_OMS_TesouroDireto_WSTDVenda_venda;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public hdSeguranca hdSegurancaValue
        {
            get
            {
                return this.hdSegurancaValueField;
            }
            set
            {
                this.hdSegurancaValueField = value;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event VendaInsCestaCompletedEventHandler VendaInsCestaCompleted;

        /// <remarks/>
        public event VendaInsItemCestaCompletedEventHandler VendaInsItemCestaCompleted;

        /// <remarks/>
        public event VendaAltItemCestaCompletedEventHandler VendaAltItemCestaCompleted;

        /// <remarks/>
        public event VendaFecharCestaCompletedEventHandler VendaFecharCestaCompleted;

        /// <remarks/>
        public event VendaConsCestaCompletedEventHandler VendaConsCestaCompleted;

        /// <remarks/>
        public event VendaConsCestaItensCompletedEventHandler VendaConsCestaItensCompleted;

        /// <remarks/>
        public event VendaVerifCondVendaCompletedEventHandler VendaVerifCondVendaCompleted;

        /// <remarks/>
        public event VendaVerifTitMercadoCompletedEventHandler VendaVerifTitMercadoCompleted;

        /// <remarks/>
        public event VendaConsTitMercadoCompletedEventHandler VendaConsTitMercadoCompleted;

        /// <remarks/>
        public event VendaConsTitVendaCompletedEventHandler VendaConsTitVendaCompleted;

        /// <remarks/>
        public event VendaConsValorTaxaCompletedEventHandler VendaConsValorTaxaCompleted;

        /// <remarks/>
        public event VendaConsValTxProvisoriaCompletedEventHandler VendaConsValTxProvisoriaCompleted;

        /// <remarks/>
        public event VendaExclCestaCompletedEventHandler VendaExclCestaCompleted;

        /// <remarks/>
        public event VendaExclItemCestaCompletedEventHandler VendaExclItemCestaCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaInsCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaInsCesta(int mercado, string negociador_cpf)
        {
            object[] results = this.Invoke("VendaInsCesta", new object[] {
                        mercado,
                        negociador_cpf});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaInsCestaAsync(int mercado, string negociador_cpf)
        {
            this.VendaInsCestaAsync(mercado, negociador_cpf, null);
        }

        /// <remarks/>
        public void VendaInsCestaAsync(int mercado, string negociador_cpf, object userState)
        {
            if ((this.VendaInsCestaOperationCompleted == null))
            {
                this.VendaInsCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaInsCestaOperationCompleted);
            }
            this.InvokeAsync("VendaInsCesta", new object[] {
                        mercado,
                        negociador_cpf}, this.VendaInsCestaOperationCompleted, userState);
        }

        private void OnVendaInsCestaOperationCompleted(object arg)
        {
            if ((this.VendaInsCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaInsCestaCompleted(this, new VendaInsCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaInsItemCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaInsItemCesta(int mercado, string negociador_cpf, int codigo_cesta, int titulo_codigo_titulo, double titulo_quantidade_compra)
        {
            object[] results = this.Invoke("VendaInsItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        titulo_codigo_titulo,
                        titulo_quantidade_compra});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaInsItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, int titulo_codigo_titulo, double titulo_quantidade_compra)
        {
            this.VendaInsItemCestaAsync(mercado, negociador_cpf, codigo_cesta, titulo_codigo_titulo, titulo_quantidade_compra, null);
        }

        /// <remarks/>
        public void VendaInsItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, int titulo_codigo_titulo, double titulo_quantidade_compra, object userState)
        {
            if ((this.VendaInsItemCestaOperationCompleted == null))
            {
                this.VendaInsItemCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaInsItemCestaOperationCompleted);
            }
            this.InvokeAsync("VendaInsItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        titulo_codigo_titulo,
                        titulo_quantidade_compra}, this.VendaInsItemCestaOperationCompleted, userState);
        }

        private void OnVendaInsItemCestaOperationCompleted(object arg)
        {
            if ((this.VendaInsItemCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaInsItemCestaCompleted(this, new VendaInsItemCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaAltItemCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaAltItemCesta(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            object[] results = this.Invoke("VendaAltItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaAltItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            this.VendaAltItemCestaAsync(mercado, negociador_cpf, codigo_cesta, xml_titulos, null);
        }

        /// <remarks/>
        public void VendaAltItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos, object userState)
        {
            if ((this.VendaAltItemCestaOperationCompleted == null))
            {
                this.VendaAltItemCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaAltItemCestaOperationCompleted);
            }
            this.InvokeAsync("VendaAltItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos}, this.VendaAltItemCestaOperationCompleted, userState);
        }

        private void OnVendaAltItemCestaOperationCompleted(object arg)
        {
            if ((this.VendaAltItemCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaAltItemCestaCompleted(this, new VendaAltItemCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaFecharCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaFecharCesta(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            object[] results = this.Invoke("VendaFecharCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaFecharCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            this.VendaFecharCestaAsync(mercado, negociador_cpf, codigo_cesta, xml_titulos, null);
        }

        /// <remarks/>
        public void VendaFecharCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos, object userState)
        {
            if ((this.VendaFecharCestaOperationCompleted == null))
            {
                this.VendaFecharCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaFecharCestaOperationCompleted);
            }
            this.InvokeAsync("VendaFecharCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos}, this.VendaFecharCestaOperationCompleted, userState);
        }

        private void OnVendaFecharCestaOperationCompleted(object arg)
        {
            if ((this.VendaFecharCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaFecharCestaCompleted(this, new VendaFecharCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaConsCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaConsCesta(int mercado, string negociador_cpf, int codigo_cesta, int codigo_titulo, string data_recompra)
        {
            object[] results = this.Invoke("VendaConsCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        codigo_titulo,
                        data_recompra});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaConsCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, int codigo_titulo, string data_recompra)
        {
            this.VendaConsCestaAsync(mercado, negociador_cpf, codigo_cesta, codigo_titulo, data_recompra, null);
        }

        /// <remarks/>
        public void VendaConsCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, int codigo_titulo, string data_recompra, object userState)
        {
            if ((this.VendaConsCestaOperationCompleted == null))
            {
                this.VendaConsCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaConsCestaOperationCompleted);
            }
            this.InvokeAsync("VendaConsCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        codigo_titulo,
                        data_recompra}, this.VendaConsCestaOperationCompleted, userState);
        }

        private void OnVendaConsCestaOperationCompleted(object arg)
        {
            if ((this.VendaConsCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaConsCestaCompleted(this, new VendaConsCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaConsCestaItens", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaConsCestaItens(int codigo_cesta, int codigo_titulo)
        {
            object[] results = this.Invoke("VendaConsCestaItens", new object[] {
                        codigo_cesta,
                        codigo_titulo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaConsCestaItensAsync(int codigo_cesta, int codigo_titulo)
        {
            this.VendaConsCestaItensAsync(codigo_cesta, codigo_titulo, null);
        }

        /// <remarks/>
        public void VendaConsCestaItensAsync(int codigo_cesta, int codigo_titulo, object userState)
        {
            if ((this.VendaConsCestaItensOperationCompleted == null))
            {
                this.VendaConsCestaItensOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaConsCestaItensOperationCompleted);
            }
            this.InvokeAsync("VendaConsCestaItens", new object[] {
                        codigo_cesta,
                        codigo_titulo}, this.VendaConsCestaItensOperationCompleted, userState);
        }

        private void OnVendaConsCestaItensOperationCompleted(object arg)
        {
            if ((this.VendaConsCestaItensCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaConsCestaItensCompleted(this, new VendaConsCestaItensCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaVerifCondVenda", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaVerifCondVenda(string negociador_cpf, int mercado)
        {
            object[] results = this.Invoke("VendaVerifCondVenda", new object[] {
                        negociador_cpf,
                        mercado});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaVerifCondVendaAsync(string negociador_cpf, int mercado)
        {
            this.VendaVerifCondVendaAsync(negociador_cpf, mercado, null);
        }

        /// <remarks/>
        public void VendaVerifCondVendaAsync(string negociador_cpf, int mercado, object userState)
        {
            if ((this.VendaVerifCondVendaOperationCompleted == null))
            {
                this.VendaVerifCondVendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaVerifCondVendaOperationCompleted);
            }
            this.InvokeAsync("VendaVerifCondVenda", new object[] {
                        negociador_cpf,
                        mercado}, this.VendaVerifCondVendaOperationCompleted, userState);
        }

        private void OnVendaVerifCondVendaOperationCompleted(object arg)
        {
            if ((this.VendaVerifCondVendaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaVerifCondVendaCompleted(this, new VendaVerifCondVendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaVerifTitMercado", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaVerifTitMercado(int mercado, int cesta_codigo)
        {
            object[] results = this.Invoke("VendaVerifTitMercado", new object[] {
                        mercado,
                        cesta_codigo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaVerifTitMercadoAsync(int mercado, int cesta_codigo)
        {
            this.VendaVerifTitMercadoAsync(mercado, cesta_codigo, null);
        }

        /// <remarks/>
        public void VendaVerifTitMercadoAsync(int mercado, int cesta_codigo, object userState)
        {
            if ((this.VendaVerifTitMercadoOperationCompleted == null))
            {
                this.VendaVerifTitMercadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaVerifTitMercadoOperationCompleted);
            }
            this.InvokeAsync("VendaVerifTitMercado", new object[] {
                        mercado,
                        cesta_codigo}, this.VendaVerifTitMercadoOperationCompleted, userState);
        }

        private void OnVendaVerifTitMercadoOperationCompleted(object arg)
        {
            if ((this.VendaVerifTitMercadoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaVerifTitMercadoCompleted(this, new VendaVerifTitMercadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaConsTitMercado", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaConsTitMercado(int mercado, int codigo_titulo, int tipo, string data_emissao, string data_vencimento, int tipo_indexador, string selic, string isin, int not_cesta)
        {
            object[] results = this.Invoke("VendaConsTitMercado", new object[] {
                        mercado,
                        codigo_titulo,
                        tipo,
                        data_emissao,
                        data_vencimento,
                        tipo_indexador,
                        selic,
                        isin,
                        not_cesta});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaConsTitMercadoAsync(int mercado, int codigo_titulo, int tipo, string data_emissao, string data_vencimento, int tipo_indexador, string selic, string isin, int not_cesta)
        {
            this.VendaConsTitMercadoAsync(mercado, codigo_titulo, tipo, data_emissao, data_vencimento, tipo_indexador, selic, isin, not_cesta, null);
        }

        /// <remarks/>
        public void VendaConsTitMercadoAsync(int mercado, int codigo_titulo, int tipo, string data_emissao, string data_vencimento, int tipo_indexador, string selic, string isin, int not_cesta, object userState)
        {
            if ((this.VendaConsTitMercadoOperationCompleted == null))
            {
                this.VendaConsTitMercadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaConsTitMercadoOperationCompleted);
            }
            this.InvokeAsync("VendaConsTitMercado", new object[] {
                        mercado,
                        codigo_titulo,
                        tipo,
                        data_emissao,
                        data_vencimento,
                        tipo_indexador,
                        selic,
                        isin,
                        not_cesta}, this.VendaConsTitMercadoOperationCompleted, userState);
        }

        private void OnVendaConsTitMercadoOperationCompleted(object arg)
        {
            if ((this.VendaConsTitMercadoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaConsTitMercadoCompleted(this, new VendaConsTitMercadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaConsTitVenda", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaConsTitVenda(string negociador_cpf, string data_emissao, string data_vencimento, string selic, string isin, int codigo_titulo, int mercado, int not_cesta, int tipo_indexador)
        {
            object[] results = this.Invoke("VendaConsTitVenda", new object[] {
                        negociador_cpf,
                        data_emissao,
                        data_vencimento,
                        selic,
                        isin,
                        codigo_titulo,
                        mercado,
                        not_cesta,
                        tipo_indexador});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaConsTitVendaAsync(string negociador_cpf, string data_emissao, string data_vencimento, string selic, string isin, int codigo_titulo, int mercado, int not_cesta, int tipo_indexador)
        {
            this.VendaConsTitVendaAsync(negociador_cpf, data_emissao, data_vencimento, selic, isin, codigo_titulo, mercado, not_cesta, tipo_indexador, null);
        }

        /// <remarks/>
        public void VendaConsTitVendaAsync(string negociador_cpf, string data_emissao, string data_vencimento, string selic, string isin, int codigo_titulo, int mercado, int not_cesta, int tipo_indexador, object userState)
        {
            if ((this.VendaConsTitVendaOperationCompleted == null))
            {
                this.VendaConsTitVendaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaConsTitVendaOperationCompleted);
            }
            this.InvokeAsync("VendaConsTitVenda", new object[] {
                        negociador_cpf,
                        data_emissao,
                        data_vencimento,
                        selic,
                        isin,
                        codigo_titulo,
                        mercado,
                        not_cesta,
                        tipo_indexador}, this.VendaConsTitVendaOperationCompleted, userState);
        }

        private void OnVendaConsTitVendaOperationCompleted(object arg)
        {
            if ((this.VendaConsTitVendaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaConsTitVendaCompleted(this, new VendaConsTitVendaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaConsValorTaxa", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaConsValorTaxa(int codigo_titulo, int codigo_cesta, int evento, string negociador_cpf)
        {
            object[] results = this.Invoke("VendaConsValorTaxa", new object[] {
                        codigo_titulo,
                        codigo_cesta,
                        evento,
                        negociador_cpf});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaConsValorTaxaAsync(int codigo_titulo, int codigo_cesta, int evento, string negociador_cpf)
        {
            this.VendaConsValorTaxaAsync(codigo_titulo, codigo_cesta, evento, negociador_cpf, null);
        }

        /// <remarks/>
        public void VendaConsValorTaxaAsync(int codigo_titulo, int codigo_cesta, int evento, string negociador_cpf, object userState)
        {
            if ((this.VendaConsValorTaxaOperationCompleted == null))
            {
                this.VendaConsValorTaxaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaConsValorTaxaOperationCompleted);
            }
            this.InvokeAsync("VendaConsValorTaxa", new object[] {
                        codigo_titulo,
                        codigo_cesta,
                        evento,
                        negociador_cpf}, this.VendaConsValorTaxaOperationCompleted, userState);
        }

        private void OnVendaConsValorTaxaOperationCompleted(object arg)
        {
            if ((this.VendaConsValorTaxaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaConsValorTaxaCompleted(this, new VendaConsValorTaxaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaConsValTxProvisoria", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaConsValTxProvisoria(string negociador_cpf, int codigo_titulo, double quantidade)
        {
            object[] results = this.Invoke("VendaConsValTxProvisoria", new object[] {
                        negociador_cpf,
                        codigo_titulo,
                        quantidade});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaConsValTxProvisoriaAsync(string negociador_cpf, int codigo_titulo, double quantidade)
        {
            this.VendaConsValTxProvisoriaAsync(negociador_cpf, codigo_titulo, quantidade, null);
        }

        /// <remarks/>
        public void VendaConsValTxProvisoriaAsync(string negociador_cpf, int codigo_titulo, double quantidade, object userState)
        {
            if ((this.VendaConsValTxProvisoriaOperationCompleted == null))
            {
                this.VendaConsValTxProvisoriaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaConsValTxProvisoriaOperationCompleted);
            }
            this.InvokeAsync("VendaConsValTxProvisoria", new object[] {
                        negociador_cpf,
                        codigo_titulo,
                        quantidade}, this.VendaConsValTxProvisoriaOperationCompleted, userState);
        }

        private void OnVendaConsValTxProvisoriaOperationCompleted(object arg)
        {
            if ((this.VendaConsValTxProvisoriaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaConsValTxProvisoriaCompleted(this, new VendaConsValTxProvisoriaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaExclCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaExclCesta(int mercado, string negociador_cpf, int codigo_cesta)
        {
            object[] results = this.Invoke("VendaExclCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaExclCestaAsync(int mercado, string negociador_cpf, int codigo_cesta)
        {
            this.VendaExclCestaAsync(mercado, negociador_cpf, codigo_cesta, null);
        }

        /// <remarks/>
        public void VendaExclCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, object userState)
        {
            if ((this.VendaExclCestaOperationCompleted == null))
            {
                this.VendaExclCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaExclCestaOperationCompleted);
            }
            this.InvokeAsync("VendaExclCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta}, this.VendaExclCestaOperationCompleted, userState);
        }

        private void OnVendaExclCestaOperationCompleted(object arg)
        {
            if ((this.VendaExclCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaExclCestaCompleted(this, new VendaExclCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/VendaExclItemCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string VendaExclItemCesta(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            object[] results = this.Invoke("VendaExclItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void VendaExclItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            this.VendaExclItemCestaAsync(mercado, negociador_cpf, codigo_cesta, xml_titulos, null);
        }

        /// <remarks/>
        public void VendaExclItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos, object userState)
        {
            if ((this.VendaExclItemCestaOperationCompleted == null))
            {
                this.VendaExclItemCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnVendaExclItemCestaOperationCompleted);
            }
            this.InvokeAsync("VendaExclItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos}, this.VendaExclItemCestaOperationCompleted, userState);
        }

        private void OnVendaExclItemCestaOperationCompleted(object arg)
        {
            if ((this.VendaExclItemCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.VendaExclItemCestaCompleted(this, new VendaExclItemCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cblc.com.br/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cblc.com.br/", IsNullable = false)]
    public partial class hdSeguranca : System.Web.Services.Protocols.SoapHeader
    {

        private string strContratoHashField;

        private string strContratoSenhaField;

        private string strLoginNomeField;

        private string strLoginSenhaField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string strContratoHash
        {
            get
            {
                return this.strContratoHashField;
            }
            set
            {
                this.strContratoHashField = value;
            }
        }

        /// <remarks/>
        public string strContratoSenha
        {
            get
            {
                return this.strContratoSenhaField;
            }
            set
            {
                this.strContratoSenhaField = value;
            }
        }

        /// <remarks/>
        public string strLoginNome
        {
            get
            {
                return this.strLoginNomeField;
            }
            set
            {
                this.strLoginNomeField = value;
            }
        }

        /// <remarks/>
        public string strLoginSenha
        {
            get
            {
                return this.strLoginSenhaField;
            }
            set
            {
                this.strLoginSenhaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaInsCestaCompletedEventHandler(object sender, VendaInsCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaInsCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaInsCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaInsItemCestaCompletedEventHandler(object sender, VendaInsItemCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaInsItemCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaInsItemCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaAltItemCestaCompletedEventHandler(object sender, VendaAltItemCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaAltItemCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaAltItemCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaFecharCestaCompletedEventHandler(object sender, VendaFecharCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaFecharCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaFecharCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaConsCestaCompletedEventHandler(object sender, VendaConsCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaConsCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaConsCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaConsCestaItensCompletedEventHandler(object sender, VendaConsCestaItensCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaConsCestaItensCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaConsCestaItensCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaVerifCondVendaCompletedEventHandler(object sender, VendaVerifCondVendaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaVerifCondVendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaVerifCondVendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaVerifTitMercadoCompletedEventHandler(object sender, VendaVerifTitMercadoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaVerifTitMercadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaVerifTitMercadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaConsTitMercadoCompletedEventHandler(object sender, VendaConsTitMercadoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaConsTitMercadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaConsTitMercadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaConsTitVendaCompletedEventHandler(object sender, VendaConsTitVendaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaConsTitVendaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaConsTitVendaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaConsValorTaxaCompletedEventHandler(object sender, VendaConsValorTaxaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaConsValorTaxaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaConsValorTaxaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaConsValTxProvisoriaCompletedEventHandler(object sender, VendaConsValTxProvisoriaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaConsValTxProvisoriaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaConsValTxProvisoriaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaExclCestaCompletedEventHandler(object sender, VendaExclCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaExclCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaExclCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void VendaExclItemCestaCompletedEventHandler(object sender, VendaExclItemCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class VendaExclItemCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal VendaExclItemCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
