//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.Site.Www {
    
    
    public partial class NovoCadastro {
        
        /// <summary>
        /// txtCadastro_PFPasso1_NomeCompleto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_NomeCompleto;
        
        /// <summary>
        /// txtCadastro_PFPasso1_Email control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_Email;
        
        /// <summary>
        /// txtCadastro_PFPasso1_EmailConfirmacao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_EmailConfirmacao;
        
        /// <summary>
        /// txtCadastro_PFPasso1_Senha control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtCadastro_PFPasso1_Senha;
        
        /// <summary>
        /// txtCadastro_PFPasso1_SenhaConfirmacao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtCadastro_PFPasso1_SenhaConfirmacao;
        
        /// <summary>
        /// txtCadastro_PFPasso1_AssEletronica control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtCadastro_PFPasso1_AssEletronica;
        
        /// <summary>
        /// txtCadastro_PFPasso1_AssEletronicaConfirmacao control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputPassword txtCadastro_PFPasso1_AssEletronicaConfirmacao;
        
        /// <summary>
        /// txtCadastro_PFPasso1_CPF control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_CPF;
        
        /// <summary>
        /// txtCadastro_PFPasso1_DataNascimento control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_DataNascimento;
        
        /// <summary>
        /// cboCadastro_PFPasso1_Sexo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect cboCadastro_PFPasso1_Sexo;
        
        /// <summary>
        /// txtCadastro_PFPasso1_Cel_DDD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_Cel_DDD;
        
        /// <summary>
        /// txtCadastro_PFPasso1_Cel_Numero control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_Cel_Numero;
        
        /// <summary>
        /// txtCadastro_PFPasso1_Tel_DDD control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_Tel_DDD;
        
        /// <summary>
        /// txtCadastro_PFPasso1_Tel_Numero control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_Tel_Numero;
        
        /// <summary>
        /// cboCadastro_PFPasso1_TipoTelefone control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect cboCadastro_PFPasso1_TipoTelefone;
        
        /// <summary>
        /// cboCadastro_PFPasso1_Conheceu control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlSelect cboCadastro_PFPasso1_Conheceu;
        
        /// <summary>
        /// pnlAssessor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlAssessor;
        
        /// <summary>
        /// txtCadastro_PFPasso1_Assessor control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlInputText txtCadastro_PFPasso1_Assessor;
        
        /// <summary>
        /// lblCadastro_PFPasso1_AssessorInicial control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblCadastro_PFPasso1_AssessorInicial;
        
        /// <summary>
        /// Sauron1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::Gradual.Site.Www.Resc.UserControls.Sauron Sauron1;
    }
}
