//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.OMS.TesouroDireto.WSDTCompra {


    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "compraSoap", Namespace = "http://www.cblc.com.br/")]
    public partial class compra : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private hdSeguranca hdSegurancaValueField;

        private System.Threading.SendOrPostCallback CompraConsTitMercadoOperationCompleted;

        private System.Threading.SendOrPostCallback CompraConsCestaOperationCompleted;

        private System.Threading.SendOrPostCallback CompraInsItemCestaOperationCompleted;

        private System.Threading.SendOrPostCallback CompraInsCestaOperationCompleted;

        private System.Threading.SendOrPostCallback CompraConsCestaItensOperationCompleted;

        private System.Threading.SendOrPostCallback CompraAltItemCestaOperationCompleted;

        private System.Threading.SendOrPostCallback CompraExclItemCestaOperationCompleted;

        private System.Threading.SendOrPostCallback CompraExclCestaOperationCompleted;

        private System.Threading.SendOrPostCallback CompraFecharCestaOperationCompleted;

        private System.Threading.SendOrPostCallback CompraCalcTaxaWSOperationCompleted;

        private System.Threading.SendOrPostCallback CompraVerifTitMercadoOperationCompleted;

        private System.Threading.SendOrPostCallback CompraVerifCondCompraOperationCompleted;

        private bool useDefaultCredentialsSetExplicitly;

        /// <remarks/>
        public compra()
        {
            this.Url = global::Gradual.OMS.TesouroDireto.Properties.Settings.Default.Gradual_OMS_TesouroDireto_WSDTCompra_compra;
            if ((this.IsLocalFileSystemWebService(this.Url) == true))
            {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else
            {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        public hdSeguranca hdSegurancaValue
        {
            get
            {
                return this.hdSegurancaValueField;
            }
            set
            {
                this.hdSegurancaValueField = value;
            }
        }

        public new string Url
        {
            get
            {
                return base.Url;
            }
            set
            {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true)
                            && (this.useDefaultCredentialsSetExplicitly == false))
                            && (this.IsLocalFileSystemWebService(value) == false)))
                {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }

        public new bool UseDefaultCredentials
        {
            get
            {
                return base.UseDefaultCredentials;
            }
            set
            {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        /// <remarks/>
        public event CompraConsTitMercadoCompletedEventHandler CompraConsTitMercadoCompleted;

        /// <remarks/>
        public event CompraConsCestaCompletedEventHandler CompraConsCestaCompleted;

        /// <remarks/>
        public event CompraInsItemCestaCompletedEventHandler CompraInsItemCestaCompleted;

        /// <remarks/>
        public event CompraInsCestaCompletedEventHandler CompraInsCestaCompleted;

        /// <remarks/>
        public event CompraConsCestaItensCompletedEventHandler CompraConsCestaItensCompleted;

        /// <remarks/>
        public event CompraAltItemCestaCompletedEventHandler CompraAltItemCestaCompleted;

        /// <remarks/>
        public event CompraExclItemCestaCompletedEventHandler CompraExclItemCestaCompleted;

        /// <remarks/>
        public event CompraExclCestaCompletedEventHandler CompraExclCestaCompleted;

        /// <remarks/>
        public event CompraFecharCestaCompletedEventHandler CompraFecharCestaCompleted;

        /// <remarks/>
        public event CompraCalcTaxaWSCompletedEventHandler CompraCalcTaxaWSCompleted;

        /// <remarks/>
        public event CompraVerifTitMercadoCompletedEventHandler CompraVerifTitMercadoCompleted;

        /// <remarks/>
        public event CompraVerifCondCompraCompletedEventHandler CompraVerifCondCompraCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraConsTitMercado", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraConsTitMercado(int mercado, int codigo_titulo, int tipo, string data_emissao, string data_vencimento, int tipo_indexador, string selic, string isin, int not_cesta)
        {
            object[] results = this.Invoke("CompraConsTitMercado", new object[] {
                        mercado,
                        codigo_titulo,
                        tipo,
                        data_emissao,
                        data_vencimento,
                        tipo_indexador,
                        selic,
                        isin,
                        not_cesta});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraConsTitMercadoAsync(int mercado, int codigo_titulo, int tipo, string data_emissao, string data_vencimento, int tipo_indexador, string selic, string isin, int not_cesta)
        {
            this.CompraConsTitMercadoAsync(mercado, codigo_titulo, tipo, data_emissao, data_vencimento, tipo_indexador, selic, isin, not_cesta, null);
        }

        /// <remarks/>
        public void CompraConsTitMercadoAsync(int mercado, int codigo_titulo, int tipo, string data_emissao, string data_vencimento, int tipo_indexador, string selic, string isin, int not_cesta, object userState)
        {
            if ((this.CompraConsTitMercadoOperationCompleted == null))
            {
                this.CompraConsTitMercadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraConsTitMercadoOperationCompleted);
            }
            this.InvokeAsync("CompraConsTitMercado", new object[] {
                        mercado,
                        codigo_titulo,
                        tipo,
                        data_emissao,
                        data_vencimento,
                        tipo_indexador,
                        selic,
                        isin,
                        not_cesta}, this.CompraConsTitMercadoOperationCompleted, userState);
        }

        private void OnCompraConsTitMercadoOperationCompleted(object arg)
        {
            if ((this.CompraConsTitMercadoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraConsTitMercadoCompleted(this, new CompraConsTitMercadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraConsCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraConsCesta(int mercado, string negociador_cpf, int codigo_cesta, string data_compra, int codigo_titulo, int cliente)
        {
            object[] results = this.Invoke("CompraConsCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        data_compra,
                        codigo_titulo,
                        cliente});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraConsCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string data_compra, int codigo_titulo, int cliente)
        {
            this.CompraConsCestaAsync(mercado, negociador_cpf, codigo_cesta, data_compra, codigo_titulo, cliente, null);
        }

        /// <remarks/>
        public void CompraConsCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string data_compra, int codigo_titulo, int cliente, object userState)
        {
            if ((this.CompraConsCestaOperationCompleted == null))
            {
                this.CompraConsCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraConsCestaOperationCompleted);
            }
            this.InvokeAsync("CompraConsCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        data_compra,
                        codigo_titulo,
                        cliente}, this.CompraConsCestaOperationCompleted, userState);
        }

        private void OnCompraConsCestaOperationCompleted(object arg)
        {
            if ((this.CompraConsCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraConsCestaCompleted(this, new CompraConsCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraInsItemCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraInsItemCesta(int mercado, string negociador_cpf, int codigo_cesta, int titulo_codigo_titulo, double titulo_quantidade_compra)
        {
            object[] results = this.Invoke("CompraInsItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        titulo_codigo_titulo,
                        titulo_quantidade_compra});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraInsItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, int titulo_codigo_titulo, double titulo_quantidade_compra)
        {
            this.CompraInsItemCestaAsync(mercado, negociador_cpf, codigo_cesta, titulo_codigo_titulo, titulo_quantidade_compra, null);
        }

        /// <remarks/>
        public void CompraInsItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, int titulo_codigo_titulo, double titulo_quantidade_compra, object userState)
        {
            if ((this.CompraInsItemCestaOperationCompleted == null))
            {
                this.CompraInsItemCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraInsItemCestaOperationCompleted);
            }
            this.InvokeAsync("CompraInsItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        titulo_codigo_titulo,
                        titulo_quantidade_compra}, this.CompraInsItemCestaOperationCompleted, userState);
        }

        private void OnCompraInsItemCestaOperationCompleted(object arg)
        {
            if ((this.CompraInsItemCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraInsItemCestaCompleted(this, new CompraInsItemCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraInsCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraInsCesta(int mercado, string negociador_cpf)
        {
            object[] results = this.Invoke("CompraInsCesta", new object[] {
                        mercado,
                        negociador_cpf});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraInsCestaAsync(int mercado, string negociador_cpf)
        {
            this.CompraInsCestaAsync(mercado, negociador_cpf, null);
        }

        /// <remarks/>
        public void CompraInsCestaAsync(int mercado, string negociador_cpf, object userState)
        {
            if ((this.CompraInsCestaOperationCompleted == null))
            {
                this.CompraInsCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraInsCestaOperationCompleted);
            }
            this.InvokeAsync("CompraInsCesta", new object[] {
                        mercado,
                        negociador_cpf}, this.CompraInsCestaOperationCompleted, userState);
        }

        private void OnCompraInsCestaOperationCompleted(object arg)
        {
            if ((this.CompraInsCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraInsCestaCompleted(this, new CompraInsCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraConsCestaItens", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraConsCestaItens(int mercado, int codigo_cesta, int codigo_titulo)
        {
            object[] results = this.Invoke("CompraConsCestaItens", new object[] {
                        mercado,
                        codigo_cesta,
                        codigo_titulo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraConsCestaItensAsync(int mercado, int codigo_cesta, int codigo_titulo)
        {
            this.CompraConsCestaItensAsync(mercado, codigo_cesta, codigo_titulo, null);
        }

        /// <remarks/>
        public void CompraConsCestaItensAsync(int mercado, int codigo_cesta, int codigo_titulo, object userState)
        {
            if ((this.CompraConsCestaItensOperationCompleted == null))
            {
                this.CompraConsCestaItensOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraConsCestaItensOperationCompleted);
            }
            this.InvokeAsync("CompraConsCestaItens", new object[] {
                        mercado,
                        codigo_cesta,
                        codigo_titulo}, this.CompraConsCestaItensOperationCompleted, userState);
        }

        private void OnCompraConsCestaItensOperationCompleted(object arg)
        {
            if ((this.CompraConsCestaItensCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraConsCestaItensCompleted(this, new CompraConsCestaItensCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraAltItemCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraAltItemCesta(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            object[] results = this.Invoke("CompraAltItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraAltItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            this.CompraAltItemCestaAsync(mercado, negociador_cpf, codigo_cesta, xml_titulos, null);
        }

        /// <remarks/>
        public void CompraAltItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos, object userState)
        {
            if ((this.CompraAltItemCestaOperationCompleted == null))
            {
                this.CompraAltItemCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraAltItemCestaOperationCompleted);
            }
            this.InvokeAsync("CompraAltItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos}, this.CompraAltItemCestaOperationCompleted, userState);
        }

        private void OnCompraAltItemCestaOperationCompleted(object arg)
        {
            if ((this.CompraAltItemCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraAltItemCestaCompleted(this, new CompraAltItemCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraExclItemCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraExclItemCesta(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            object[] results = this.Invoke("CompraExclItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraExclItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            this.CompraExclItemCestaAsync(mercado, negociador_cpf, codigo_cesta, xml_titulos, null);
        }

        /// <remarks/>
        public void CompraExclItemCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos, object userState)
        {
            if ((this.CompraExclItemCestaOperationCompleted == null))
            {
                this.CompraExclItemCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraExclItemCestaOperationCompleted);
            }
            this.InvokeAsync("CompraExclItemCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos}, this.CompraExclItemCestaOperationCompleted, userState);
        }

        private void OnCompraExclItemCestaOperationCompleted(object arg)
        {
            if ((this.CompraExclItemCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraExclItemCestaCompleted(this, new CompraExclItemCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraExclCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraExclCesta(int mercado, string negociador_cpf, int codigo_cesta)
        {
            object[] results = this.Invoke("CompraExclCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraExclCestaAsync(int mercado, string negociador_cpf, int codigo_cesta)
        {
            this.CompraExclCestaAsync(mercado, negociador_cpf, codigo_cesta, null);
        }

        /// <remarks/>
        public void CompraExclCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, object userState)
        {
            if ((this.CompraExclCestaOperationCompleted == null))
            {
                this.CompraExclCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraExclCestaOperationCompleted);
            }
            this.InvokeAsync("CompraExclCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta}, this.CompraExclCestaOperationCompleted, userState);
        }

        private void OnCompraExclCestaOperationCompleted(object arg)
        {
            if ((this.CompraExclCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraExclCestaCompleted(this, new CompraExclCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraFecharCesta", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraFecharCesta(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            object[] results = this.Invoke("CompraFecharCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraFecharCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos)
        {
            this.CompraFecharCestaAsync(mercado, negociador_cpf, codigo_cesta, xml_titulos, null);
        }

        /// <remarks/>
        public void CompraFecharCestaAsync(int mercado, string negociador_cpf, int codigo_cesta, string xml_titulos, object userState)
        {
            if ((this.CompraFecharCestaOperationCompleted == null))
            {
                this.CompraFecharCestaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraFecharCestaOperationCompleted);
            }
            this.InvokeAsync("CompraFecharCesta", new object[] {
                        mercado,
                        negociador_cpf,
                        codigo_cesta,
                        xml_titulos}, this.CompraFecharCestaOperationCompleted, userState);
        }

        private void OnCompraFecharCestaOperationCompleted(object arg)
        {
            if ((this.CompraFecharCestaCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraFecharCestaCompleted(this, new CompraFecharCestaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraCalcTaxaWS", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraCalcTaxaWS(int mercado, string negociador_cpf, string xml_titulos)
        {
            object[] results = this.Invoke("CompraCalcTaxaWS", new object[] {
                        mercado,
                        negociador_cpf,
                        xml_titulos});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraCalcTaxaWSAsync(int mercado, string negociador_cpf, string xml_titulos)
        {
            this.CompraCalcTaxaWSAsync(mercado, negociador_cpf, xml_titulos, null);
        }

        /// <remarks/>
        public void CompraCalcTaxaWSAsync(int mercado, string negociador_cpf, string xml_titulos, object userState)
        {
            if ((this.CompraCalcTaxaWSOperationCompleted == null))
            {
                this.CompraCalcTaxaWSOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraCalcTaxaWSOperationCompleted);
            }
            this.InvokeAsync("CompraCalcTaxaWS", new object[] {
                        mercado,
                        negociador_cpf,
                        xml_titulos}, this.CompraCalcTaxaWSOperationCompleted, userState);
        }

        private void OnCompraCalcTaxaWSOperationCompleted(object arg)
        {
            if ((this.CompraCalcTaxaWSCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraCalcTaxaWSCompleted(this, new CompraCalcTaxaWSCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraVerifTitMercado", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraVerifTitMercado(int mercado, int cesta_codigo)
        {
            object[] results = this.Invoke("CompraVerifTitMercado", new object[] {
                        mercado,
                        cesta_codigo});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraVerifTitMercadoAsync(int mercado, int cesta_codigo)
        {
            this.CompraVerifTitMercadoAsync(mercado, cesta_codigo, null);
        }

        /// <remarks/>
        public void CompraVerifTitMercadoAsync(int mercado, int cesta_codigo, object userState)
        {
            if ((this.CompraVerifTitMercadoOperationCompleted == null))
            {
                this.CompraVerifTitMercadoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraVerifTitMercadoOperationCompleted);
            }
            this.InvokeAsync("CompraVerifTitMercado", new object[] {
                        mercado,
                        cesta_codigo}, this.CompraVerifTitMercadoOperationCompleted, userState);
        }

        private void OnCompraVerifTitMercadoOperationCompleted(object arg)
        {
            if ((this.CompraVerifTitMercadoCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraVerifTitMercadoCompleted(this, new CompraVerifTitMercadoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("hdSegurancaValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://www.cblc.com.br/CompraVerifCondCompra", RequestNamespace = "http://www.cblc.com.br/", ResponseNamespace = "http://www.cblc.com.br/", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CompraVerifCondCompra(string negociador_cpf, int mercado)
        {
            object[] results = this.Invoke("CompraVerifCondCompra", new object[] {
                        negociador_cpf,
                        mercado});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CompraVerifCondCompraAsync(string negociador_cpf, int mercado)
        {
            this.CompraVerifCondCompraAsync(negociador_cpf, mercado, null);
        }

        /// <remarks/>
        public void CompraVerifCondCompraAsync(string negociador_cpf, int mercado, object userState)
        {
            if ((this.CompraVerifCondCompraOperationCompleted == null))
            {
                this.CompraVerifCondCompraOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompraVerifCondCompraOperationCompleted);
            }
            this.InvokeAsync("CompraVerifCondCompra", new object[] {
                        negociador_cpf,
                        mercado}, this.CompraVerifCondCompraOperationCompleted, userState);
        }

        private void OnCompraVerifCondCompraOperationCompleted(object arg)
        {
            if ((this.CompraVerifCondCompraCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CompraVerifCondCompraCompleted(this, new CompraVerifCondCompraCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }

        private bool IsLocalFileSystemWebService(string url)
        {
            if (((url == null)
                        || (url == string.Empty)))
            {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024)
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0)))
            {
                return true;
            }
            return false;
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://www.cblc.com.br/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace = "http://www.cblc.com.br/", IsNullable = false)]
    public partial class hdSeguranca : System.Web.Services.Protocols.SoapHeader
    {

        private string strContratoHashField;

        private string strContratoSenhaField;

        private string strLoginNomeField;

        private string strLoginSenhaField;

        private System.Xml.XmlAttribute[] anyAttrField;

        /// <remarks/>
        public string strContratoHash
        {
            get
            {
                return this.strContratoHashField;
            }
            set
            {
                this.strContratoHashField = value;
            }
        }

        /// <remarks/>
        public string strContratoSenha
        {
            get
            {
                return this.strContratoSenhaField;
            }
            set
            {
                this.strContratoSenhaField = value;
            }
        }

        /// <remarks/>
        public string strLoginNome
        {
            get
            {
                return this.strLoginNomeField;
            }
            set
            {
                this.strLoginNomeField = value;
            }
        }

        /// <remarks/>
        public string strLoginSenha
        {
            get
            {
                return this.strLoginSenhaField;
            }
            set
            {
                this.strLoginSenhaField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr
        {
            get
            {
                return this.anyAttrField;
            }
            set
            {
                this.anyAttrField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraConsTitMercadoCompletedEventHandler(object sender, CompraConsTitMercadoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraConsTitMercadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraConsTitMercadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraConsCestaCompletedEventHandler(object sender, CompraConsCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraConsCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraConsCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraInsItemCestaCompletedEventHandler(object sender, CompraInsItemCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraInsItemCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraInsItemCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraInsCestaCompletedEventHandler(object sender, CompraInsCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraInsCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraInsCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraConsCestaItensCompletedEventHandler(object sender, CompraConsCestaItensCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraConsCestaItensCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraConsCestaItensCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraAltItemCestaCompletedEventHandler(object sender, CompraAltItemCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraAltItemCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraAltItemCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraExclItemCestaCompletedEventHandler(object sender, CompraExclItemCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraExclItemCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraExclItemCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraExclCestaCompletedEventHandler(object sender, CompraExclCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraExclCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraExclCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraFecharCestaCompletedEventHandler(object sender, CompraFecharCestaCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraFecharCestaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraFecharCestaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraCalcTaxaWSCompletedEventHandler(object sender, CompraCalcTaxaWSCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraCalcTaxaWSCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraCalcTaxaWSCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraVerifTitMercadoCompletedEventHandler(object sender, CompraVerifTitMercadoCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraVerifTitMercadoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraVerifTitMercadoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void CompraVerifCondCompraCompletedEventHandler(object sender, CompraVerifCondCompraCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CompraVerifCondCompraCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CompraVerifCondCompraCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
