//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.Site.Www.Resc.UserControls {
    
    
    public partial class PainelDeLogin {
        
        /// <summary>
        /// pnlNavegacaoLogin_DadosDoUsuario control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl pnlNavegacaoLogin_DadosDoUsuario;
        
        /// <summary>
        /// lblUsuario_Nome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblUsuario_Nome;
        
        /// <summary>
        /// lblUsuario_Conta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblUsuario_Conta;
        
        /// <summary>
        /// lblUsuario_Perfil control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblUsuario_Perfil;
        
        /// <summary>
        /// lblUsuario_Acesso control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblUsuario_Acesso;
        
        /// <summary>
        /// pnlGradSite_MinhaConta_Cadastro_Login_ClienteLogin control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlGradSite_MinhaConta_Cadastro_Login_ClienteLogin;
        
        /// <summary>
        /// pnlGradSite_MinhaConta_Cadastro_Login_ClienteLogado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlGradSite_MinhaConta_Cadastro_Login_ClienteLogado;
        
        /// <summary>
        /// txtGradSite_MinhaConta_Cadastro_Login_UsuarioLogado_Nome control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl txtGradSite_MinhaConta_Cadastro_Login_UsuarioLogado_Nome;
        
        /// <summary>
        /// txtGradSite_MinhaConta_Cadastro_Login_Usuario_Logout control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.LinkButton txtGradSite_MinhaConta_Cadastro_Login_Usuario_Logout;
        
        /// <summary>
        /// pnlGradSite_Password control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel pnlGradSite_Password;
    }
}
