///////////////////////////////////////////////////////////
//  ReceberItemAutomacaoOrdemResponse.cs
//  Implementation of the Class ReceberItemAutomacaoOrdemResponse
//  Generated by Enterprise Architect
//  Created on:      23-abr-2010 15:48:10
//  Original author: amiguel
///////////////////////////////////////////////////////////




using Gradual.OMS.Contratos.Automacao.Ordens.Dados;
using Gradual.OMS.Contratos.Ordens.Dados;
using Gradual.OMS.Contratos.Comum.Mensagens;
namespace Gradual.OMS.Contratos.Automacao.Ordens.Mensagens {
	public class ReceberItemAutomacaoOrdemResponse : MensagemResponseBase {

        public ItemAutomacaoOrdemInfo ItemAutomacaoOrdemInfo { get; set; }
        public OrdemInfo OrdemInfo { get; set; }

		public ReceberItemAutomacaoOrdemResponse(){

		}


	}//end ReceberItemAutomacaoOrdemResponse

}//end namespace Mensagens