///////////////////////////////////////////////////////////
//  ReceberItemAutomacaoOrdemRequest.cs
//  Implementation of the Class ReceberItemAutomacaoOrdemRequest
//  Generated by Enterprise Architect
//  Created on:      23-abr-2010 15:47:58
//  Original author: amiguel
///////////////////////////////////////////////////////////




using Gradual.OMS.Contratos.Comum.Mensagens;
namespace Gradual.OMS.Contratos.Automacao.Ordens.Mensagens {
    public class ReceberItemAutomacaoOrdemRequest : MensagemRequestBase
    {

        public string CodigoItemAutomacaoOrdem { get; set; }
        public bool IncluirDetalhesDeOrdem { get; set; }

		public ReceberItemAutomacaoOrdemRequest(){

		}


	}//end ReceberItemAutomacaoOrdemRequest

}//end namespace Mensagens