//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.Site.Www.Resc.UserControls {
    
    
    public partial class MapaDoSite {
        
        /// <summary>
        /// lblMapaSiteComoInvestirAbraSuaConta control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMapaSiteComoInvestirAbraSuaConta;
        
        /// <summary>
        /// lblMapaSiteMinhaContaCadastroMeuCadastro control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblMapaSiteMinhaContaCadastroMeuCadastro;
    }
}
