//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.Intranet.Www.Intranet.Posicao {
    
    
    public partial class Financeiro {
        
        /// <summary>
        /// Head1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlHead Head1;
        
        /// <summary>
        /// form1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlForm form1;
        
        /// <summary>
        /// lblCodigoCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblCodigoCliente;
        
        /// <summary>
        /// lblNomeCliente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblNomeCliente;
        
        /// <summary>
        /// lblSaldoDisponivel_ValorParaDia_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoDisponivel_ValorParaDia_PosNeg;
        
        /// <summary>
        /// lblSaldoDisponivel_ValorParaDia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoDisponivel_ValorParaDia;
        
        /// <summary>
        /// lblSaldoDisponivel_ResgateParaDia_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoDisponivel_ResgateParaDia_PosNeg;
        
        /// <summary>
        /// lblSaldoDisponivel_ResgateParaDia control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoDisponivel_ResgateParaDia;
        
        /// <summary>
        /// lblLimite_TotalDisponivelAVista_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLimite_TotalDisponivelAVista_PosNeg;
        
        /// <summary>
        /// lblLimite_TotalDisponivelAVista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLimite_TotalDisponivelAVista;
        
        /// <summary>
        /// lblLimite_TotalDisponivelParaOpcoes_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLimite_TotalDisponivelParaOpcoes_PosNeg;
        
        /// <summary>
        /// lblLimite_TotalDisponivelParaOpcoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLimite_TotalDisponivelParaOpcoes;
        
        /// <summary>
        /// lblLimite_DeCreditoAVista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLimite_DeCreditoAVista;
        
        /// <summary>
        /// lblLimite_DeCreditoParaOpcoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLimite_DeCreditoParaOpcoes;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoTotal_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoTotal_PosNeg;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoTotal control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoTotal;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoD1_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoD1_PosNeg;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoD1 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoD1;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoD2_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoD2_PosNeg;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoD2 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoD2;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoD3_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoD3_PosNeg;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoD3 control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoD3;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoContaMargem_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoContaMargem_PosNeg;
        
        /// <summary>
        /// lblLancamento_AcoesProjetadoContaMargem control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblLancamento_AcoesProjetadoContaMargem;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_ComprasExecutadas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_ComprasExecutadas;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_VendasExecutadas control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_VendasExecutadas;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_TotalAVista_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_TotalAVista_PosNeg;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_TotalAVista control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_TotalAVista;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_ComprasDeOpcoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_ComprasDeOpcoes;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_VendasDeOpcoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_VendasDeOpcoes;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_TotalDeOpcoes_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_TotalDeOpcoes_PosNeg;
        
        /// <summary>
        /// lblOperacoesRealizadasDoDia_TotalDeOpcoes control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesRealizadasDoDia_TotalDeOpcoes;
        
        /// <summary>
        /// lblOperacoesNaoRealizadasDoDia_TotalEmAberto_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesNaoRealizadasDoDia_TotalEmAberto_PosNeg;
        
        /// <summary>
        /// lblOperacoesNaoRealizadasDoDia_TotalEmAberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesNaoRealizadasDoDia_TotalEmAberto;
        
        /// <summary>
        /// lblOperacoesNaoRealizadasDoDia_ComprasEmAberto_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesNaoRealizadasDoDia_ComprasEmAberto_PosNeg;
        
        /// <summary>
        /// lblOperacoesNaoRealizadasDoDia_ComprasEmAberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesNaoRealizadasDoDia_ComprasEmAberto;
        
        /// <summary>
        /// lblOperacoesNaoRealizadasDoDia_VendasEmAberto_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesNaoRealizadasDoDia_VendasEmAberto_PosNeg;
        
        /// <summary>
        /// lblOperacoesNaoRealizadasDoDia_VendasEmAberto control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblOperacoesNaoRealizadasDoDia_VendasEmAberto;
        
        /// <summary>
        /// lblSaldoProjetado_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoProjetado_PosNeg;
        
        /// <summary>
        /// lblSaldoProjetado control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoProjetado;
        
        /// <summary>
        /// lblSaldoTotalEmContaCorrente_PosNeg control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoTotalEmContaCorrente_PosNeg;
        
        /// <summary>
        /// lblSaldoTotalEmContaCorrente control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Literal lblSaldoTotalEmContaCorrente;
    }
}
