create or replace PROCEDURE PCCSALDOPROJETADO(PCODCLIENTE IN VARCHAR2, PSALDO OUT NUMBER, PD1 OUT NUMBER, PD2 OUT NUMBER, PD3 OUT NUMBER) IS
 SINSERT          VARCHAR2(500);
 NINT             NUMBER(1)    := 0;
 NSALDOINICIAL    NUMBER(15,2) := 0;
 NSALDOATUALIZADO NUMBER(15,2) := 0;
 DDATSALDO        DATE;
 ND1      NUMBER(15,2) := 0;
 ND2      NUMBER(15,2) := 0;
 ND3        NUMBER(15,2) := 0;
 DDATPREGAO    DATE;
 NACUMULADO    NUMBER(15,2);
 NSID     NUMBER(10);

 CURSOR C1 IS
 SELECT
     CD_CLIENTE,
     SUM(VL_LANCAMENTO) VL_LANCAMENTO,
     DT_LIQUIDACAO
 FROM
     V_TCCMOVTO
 WHERE
     CD_CLIENTE = PCODCLIENTE
 AND DT_LIQUIDACAO > DDATPREGAO
 GROUP BY
     CD_CLIENTE,
     DT_LIQUIDACAO
 UNION
 SELECT
     A.CD_CLIENTE,
     SUM(A.VL_LIQNOT) VL_LANCAMENTO,
     A.PZ_PROJ_CC DT_LIQUIDACAO
 FROM
     V_TBOFINCL A
 WHERE
     A.CD_CLIENTE        = PCODCLIENTE
 AND A.CD_CLIENTE_LIQFIN = A.CD_CLIENTE_CC
 AND A.DT_NEGOCIO        = DDATPREGAO
 GROUP BY
     CD_CLIENTE,
     PZ_PROJ_CC
 ORDER BY
     DT_LIQUIDACAO;

 CURSOR C3 IS
 SELECT
     SUM(VL_LANCAMENTO) VL_LANCAMENTO
 FROM
     V_TCCMOVTO
 WHERE
     CD_CLIENTE = PCODCLIENTE
 AND DT_LIQUIDACAO BETWEEN DDATSALDO AND DDATPREGAO;


 CURSOR C4 IS
 SELECT
    ROWNUM D,
    A.PZ_PROJ_CC DATA
 FROM
    (
       SELECT DISTINCT PZ_PROJ_CC FROM TBOCALE A, TMFDATPRE B WHERE A.PZ_PROJ_CC > B.DT_MOV ORDER BY 1
    ) A;

 BEGIN

     BEGIN
        SELECT
        DT_DATMOV INTO DDATPREGAO
        FROM
        TORDATMOV;
     EXCEPTION
     WHEN OTHERS THEN
        SELECT DT_MOV INTO DDATPREGAO FROM TMFDATPRE;
     END;

     BEGIN
        SELECT
           NVL(VL_INICIAL_DIS,0), DT_SALDO INTO NSALDOINICIAL, DDATSALDO
        FROM
           V_TCCSALDO
        WHERE
           CD_CLIENTE = PCODCLIENTE
        AND DT_SALDO = TRUNC(DDATPREGAO, 'MM');
     EXCEPTION
     WHEN OTHERS THEN
        NSALDOINICIAL := 0;
        DDATSALDO     := TRUNC(DDATPREGAO,'MM');
     END;

     NSALDOATUALIZADO := NVL(NSALDOINICIAL,0);
     --
     FOR R3 IN C3 LOOP
         NSALDOATUALIZADO := NSALDOATUALIZADO + NVL(R3.VL_LANCAMENTO,0);
     END LOOP;


     FOR R1 IN C1 LOOP
        FOR R4 IN C4 LOOP
            IF R1.DT_LIQUIDACAO = R4.DATA THEN
               IF R4.D = 1 THEN
                  ND1 := ND1 + R1.VL_LANCAMENTO;
               ELSIF R4.D = 2 THEN
                  ND2 := ND2 + R1.VL_LANCAMENTO;
               ELSIF R4.D = 3 THEN
                  ND3 := ND3 + R1.VL_LANCAMENTO;
               END IF;
            END IF;
        END LOOP;
     END LOOP;
     --
     PSALDO := NSALDOATUALIZADO;
     PD1    := ND1;
     PD2    := ND2;
     PD3    := ND3;
 END PCCSALDOPROJETADO;
 