
SELECT
' ' AS "Linha",
TO_CHAR(TORCOMI.DT_NEGOCIO, 'DD/MM/YYYY') as "Data",
TSCCLIBOL.CD_CLIENTE as "Cliente",
TSCCLIGER.NM_CLIENTE as "Nome Cliente",
ABS(TSCCLIBOL.PC_CORCOR_PRIN) as "% Repasse",
'SP' as "Praca",
TORCOMI.CD_NATOPE as "Operacao",
TORCOMI.TP_NEGOCIO as "Tipo",
'OPERACAO FINAL' as "Tipo1",
TORCOMI.CD_NEGOCIO as "Papel",
SUM (TORCOMI.QT_QTDESP) as "QTD",
TORNEGD.VL_NEGOCIO as "Preco",
SUM (TORCOMI.QT_QTDESP) * TORNEGD.VL_NEGOCIO as "Financeiro"
FROM
TSCCLIBOL , TSCCLIGER, TORCOMI, TORNEGD 
WHERE
TSCCLIBOL.CD_CLIENTE_LIQFIN = 29955                   AND
TSCCLIBOL.CD_CPFCGC         = TSCCLIGER.CD_CPFCGC     AND
TSCCLIBOL.DT_NASC_FUND      = TSCCLIGER.DT_NASC_FUND  AND
TSCCLIBOL.CD_CON_DEP        = TSCCLIGER.CD_CON_DEP    AND
TSCCLIBOL.CD_CLIENTE        = TORCOMI.CD_CLIENTE      AND
TORCOMI.DT_NEGOCIO          = TO_DATE('05/08/2015', 'DD/MM/YYYY') AND 
TORCOMI.DT_NEGOCIO          = TORNEGD.DT_PREGAO  	  AND 
TORCOMI.NR_NEGOCIO          = TORNEGD.NR_NEGOCIO      AND 
TORCOMI.CD_NEGOCIO          = TORNEGD.CD_NEGOCIO      AND 
TORCOMI.CD_NATOPE           = TORNEGD.CD_NATOPE   
GROUP BY 
TORCOMI.DT_NEGOCIO,
TSCCLIBOL.CD_CLIENTE,
TSCCLIGER.NM_CLIENTE,
TSCCLIBOL.PC_CORCOR_PRIN,
TORCOMI.CD_NATOPE,
TORCOMI.TP_NEGOCIO,
TORCOMI.CD_NEGOCIO,
TORNEGD.VL_NEGOCIO