///////////////////////////////////////////////////////////
//  BolsaInfo.cs
//  Implementation of the Class BolsaInfo
//  Generated by Enterprise Architect
//  Created on:      26-jul-2010 17:43:16
//  Original author: amiguel
///////////////////////////////////////////////////////////




namespace Gradual.OMS.Risco.RegraLib.Dados {
	public enum BolsaInfo : int {

		BMF = 2,
		BOVESPA = 1

	}//end BolsaInfo

}//end namespace Dados