///////////////////////////////////////////////////////////
//  ParametroRiscoInfo.cs
//  Implementation of the Class ParametroRiscoInfo
//  Generated by Enterprise Architect
//  Created on:      26-jul-2010 17:43:27
//  Original author: amiguel
///////////////////////////////////////////////////////////




using Gradual.OMS.Risco.RegraLib.Dados;
using Gradual.OMS.Library;
using System;

namespace Gradual.OMS.Risco.RegraLib.Dados 
{
	/// <summary>
	/// Parametro do sistema de risco.
	/// </summary>
    [Serializable]
    public class ParametroRiscoInfo : ICodigoEntidade
    {

		public ParametroRiscoInfo(){

		}

		~ParametroRiscoInfo(){

		}

		/// <summary>
		/// Nome do Parametro.
		/// </summary>
        public string NomeParametro
        {
            get;
            set;
        }

		/// <summary>
		/// Codigo do parametro.
		/// </summary>
		public int CodigoParametro{
			get;
			set;
		}

		public BolsaInfo Bolsa{
			get;
			set;
		}

        public string NameSpace { get; set; }

        public string Metodo { get; set; }



        #region ICodigoEntidade Members

        public string ReceberCodigo()
        {
            return this.CodigoParametro.ToString();
        }

        #endregion
    }//end ParametroRiscoInfo

}//end namespace Dados