//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3603
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsAutenticacao.AutenticacaoSoap")]
    public interface AutenticacaoSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AutenticarUsuario", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespostaBase))]
        Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao.AutenticarUsuarioResponse AutenticarUsuario(Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao.AutenticarUsuarioRequest pRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarUsuarioRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoOuEmailDoUsuarioField;
        
        private string senhaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodigoOuEmailDoUsuario {
            get {
                return this.codigoOuEmailDoUsuarioField;
            }
            set {
                this.codigoOuEmailDoUsuarioField = value;
                this.RaisePropertyChanged("CodigoOuEmailDoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Senha {
            get {
                return this.senhaField;
            }
            set {
                this.senhaField = value;
                this.RaisePropertyChanged("Senha");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(AutenticarUsuarioResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespostaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusRespostaField;
        
        private string descricaoRespostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusResposta {
            get {
                return this.statusRespostaField;
            }
            set {
                this.statusRespostaField = value;
                this.RaisePropertyChanged("StatusResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DescricaoResposta {
            get {
                return this.descricaoRespostaField;
            }
            set {
                this.descricaoRespostaField = value;
                this.RaisePropertyChanged("DescricaoResposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "2.0.50727.3082")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class AutenticarUsuarioResponse : RespostaBase {
        
        private string codigoDaSessaoField;
        
        private string codigoCblcDoUsuarioField;
        
        private string codigoBmfDoUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodigoDaSessao {
            get {
                return this.codigoDaSessaoField;
            }
            set {
                this.codigoDaSessaoField = value;
                this.RaisePropertyChanged("CodigoDaSessao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CodigoCblcDoUsuario {
            get {
                return this.codigoCblcDoUsuarioField;
            }
            set {
                this.codigoCblcDoUsuarioField = value;
                this.RaisePropertyChanged("CodigoCblcDoUsuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string CodigoBmfDoUsuario {
            get {
                return this.codigoBmfDoUsuarioField;
            }
            set {
                this.codigoBmfDoUsuarioField = value;
                this.RaisePropertyChanged("CodigoBmfDoUsuario");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface AutenticacaoSoapChannel : Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao.AutenticacaoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class AutenticacaoSoapClient : System.ServiceModel.ClientBase<Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao.AutenticacaoSoap>, Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao.AutenticacaoSoap {
        
        public AutenticacaoSoapClient() {
        }
        
        public AutenticacaoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacaoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacaoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacaoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao.AutenticarUsuarioResponse AutenticarUsuario(Gradual.StockMarket.Excel2003.AddIn.WsAutenticacao.AutenticarUsuarioRequest pRequest) {
            return base.Channel.AutenticarUsuario(pRequest);
        }
    }
}
