//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StockMarket.Excel2007.WsPlataforma {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WsPlataforma.PlataformaSoap")]
    public interface PlataformaSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/BuscarCarteirasComAtivos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RespostaBase))]
        StockMarket.Excel2007.WsPlataforma.BuscarCarteirasComAtivosResponse BuscarCarteirasComAtivos(StockMarket.Excel2007.WsPlataforma.BuscarCarteirasComAtivosRequest pRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarCarteirasComAtivosRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoDoUsuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CodigoDoUsuario {
            get {
                return this.codigoDoUsuarioField;
            }
            set {
                this.codigoDoUsuarioField = value;
                this.RaisePropertyChanged("CodigoDoUsuario");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BuscarCarteirasComAtivosResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RespostaBase : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string statusRespostaField;
        
        private string descricaoRespostaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StatusResposta {
            get {
                return this.statusRespostaField;
            }
            set {
                this.statusRespostaField = value;
                this.RaisePropertyChanged("StatusResposta");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string DescricaoResposta {
            get {
                return this.descricaoRespostaField;
            }
            set {
                this.descricaoRespostaField = value;
                this.RaisePropertyChanged("DescricaoResposta");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34234")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class BuscarCarteirasComAtivosResponse : RespostaBase {
        
        private string[] carteirasField;
        
        private string[] ativosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] Carteiras {
            get {
                return this.carteirasField;
            }
            set {
                this.carteirasField = value;
                this.RaisePropertyChanged("Carteiras");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public string[] Ativos {
            get {
                return this.ativosField;
            }
            set {
                this.ativosField = value;
                this.RaisePropertyChanged("Ativos");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlataformaSoapChannel : StockMarket.Excel2007.WsPlataforma.PlataformaSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlataformaSoapClient : System.ServiceModel.ClientBase<StockMarket.Excel2007.WsPlataforma.PlataformaSoap>, StockMarket.Excel2007.WsPlataforma.PlataformaSoap {
        
        public PlataformaSoapClient() {
        }
        
        public PlataformaSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlataformaSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlataformaSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlataformaSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public StockMarket.Excel2007.WsPlataforma.BuscarCarteirasComAtivosResponse BuscarCarteirasComAtivos(StockMarket.Excel2007.WsPlataforma.BuscarCarteirasComAtivosRequest pRequest) {
            return base.Channel.BuscarCarteirasComAtivos(pRequest);
        }
    }
}
